### ISSUE TITLE
Add an appointment to delete an appointment?

### ISSUE THREAD

**Issue by scytail** [bspymaster/Appointment-Calendar#6]
@jmitt508, the deleteApt() method requires an appointment to be created to destroy another appointment. Is there a better way to find an appointment (maybe appointment names need another identifier, or search by the description or startDate)? Additionally, I don't think using "==" to compare to Appointment instances will ever return true, since the two instances will be located at different pointers and thus never be equal from the computer's perspective. Ideas?

**Comment by jmitt508** [comment]
I changed how the appointments are compared by using the individual parts.
